# Generated by Django 4.2.6 on 2023-11-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
