# Generated by Django 4.2.6 on 2023-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('E', 'Экономика'), ('S', 'Наука'), ('IT', 'IT'), ('T', 'Путешествия'), ('C', 'Культура'), ('S', 'Спорт')], max_length=25, verbose_name='Категории'),
        ),
    ]
