# Generated by Django 4.2.6 on 2023-11-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='nickname',
            new_name='username',
        ),
    ]
