# Generated by Django 4.2.6 on 2023-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_nickname_account_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='nickname',
        ),
    ]
